baseURL = "/"
languageCode = "en-us"
title = "sparklyr"
theme = "rstudio-docs-theme"
metadataformat = "yaml"
uglyURLs = true
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$", "\\.log$"]
preserveTaxonomyNames = true


[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
	# General information
	author = "Javier Luraschii"
	description = "Documentation for the Spark for R interface"
	copyright = "Copyright 2017, RStudio, Inc."
	repo = "https://github.com/rstudio/sparklyr"

[[menu.main]]
  weight = 10
	name   = "dplyr"
	url    = "/articles/guides-dplyr"